WIDTH = 1280
HEIGHT = 720
FPS = 60
PLAYER_SPEED = 250
PLAYER_SIZE = 50
ENEMY_SPEED = 200
ENEMY_SIZE_MIN = 10
ENEMY_SIZE_MAX = 25
# per second
SPAWN_COUNT_START = 5
SPAWN_COUNT_MAX = 12
# +1 spawn count per SPAWN_COUNT_ACCELERATION spawn iterations
SPAWN_COUNT_ACCELERATION = 40
